export const SET_CART = 'SET_CART'
export const SET_TICKET = 'SET_TICKET'
export const ADD_TICKET = 'ADD_TICKET'
export const DELETE_TICKET = 'DELETE_TICKET'
export const DELETE_TICKET_DESIGNATED = 'DELETE_TICKET_DESIGNATED'
export const CHOOSE_TICKET_TYPE = 'CHOOSE_TICKET_TYPE'

export default {
  SET_TICKET,
  ADD_TICKET,
  DELETE_TICKET,
  DELETE_TICKET_DESIGNATED,
  CHOOSE_TICKET_TYPE,
  SET_CART

}

