export default {
  SHOWS: 'SHOWS',
  LIST_SHOWS: 'LIST_SHOWS',
  SEARCH_SHOW: 'SEARCH_SHOW',
  SEARCHING: 'SEARCHING',
  RESET_SEARCH: 'RESET_SEARCH',
  CLEAR_SHOW: 'CLEAR_SHOW',
  ADD_SEARCH_FORM: 'ADD_SEARCH_FORM'
  ,  SET_TOTAL_RECORD: 'SET_TOTAL_RECORD'
}
